[game]
hostname = "☢️S.T.A.L.K.E.R. [EN Test] ☣️"
desc = "Server in S.T.A.L.K.E.R. setting. Now in English!"
map_pool = "STDefaultMapPool"
maxplayers = 140
soft_max_players = 80
map_rotation = false
role_timers = true
peaceful_end = false
contraband_examine = false

[rules]
time = 30.0

[netres]
limit = 25.0

[whitelist]
enabled = true

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[infolinks]
discord = "https://discord.gg/SnUSV76zR3"
patreon = "https://boosty.to/stalkerss14"



[npc]
max_updates = 150

[hub]
advertise = true
tags = "lang:en,rp:high,region:us_e"
hub_urls = "https://hub.spacestation14.com/"

[net]
sendbuffersize = 393213
receivebuffersize = 393213
pvs_range = 25.0
tickrate = 30
max_buffer_size = 1024
log_late_msg = false

[auth]
mode = 1
server = "https://auth.spacestation14.com/"

[events]
enabled = false

[console]
login_host_user = "coolmankid12345"

[crewmanifest]
no_entity = false
