- type: job
  id: StalkerAnomalist
  name: The Anomalist
  icon: tec
  description: Studying and preserving the zone. Active use of anomalies and artifacts. Creating new anomalies and artifacts. Creating equipment based on anomalies/artifacts or for working with anomalies.
  playTimeTracker: JobStalkerAnomalist
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerAnomalist
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: AnomalistGear
  supervisors: Вы работаете сами на себя
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      groups:
        - Anomalist
    - type: Bands
      band: Stalker
      bandIcon: tec
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3

- type: startingGear
  id: AnomalistGear
  equipment:
    id: AnomalistPDA
    head: ClothingHeadHatBeaniehat
    legs: ClothingLegsAnomalistTechnician
    torso: ClothingTorsoAnomalistTechnician
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackDuffelHikingVSRF
    neck: ClothingNeckDogtagStalker

- type: job
  id: StalkerAnomalistGuardian
  name: Guardian
  icon: tec
  description: Studying and preserving the zone. Active use of anomalies and artifacts. Creating new anomalies and artifacts. Creating equipment based on anomalies/artifacts or for working with anomalies.
  playTimeTracker: StalkerAnomalistGuardian
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: StalkerAnomalistGuardian
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: AnomalistGear
  supervisors: Вы работаете сами на себя
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      groups:
        - Anomalist
        - AnomalistGuardian
    - type: Bands
      band: Stalker
      bandIcon: tec
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3
