- type: job
  id: StalkerDolg
  name: боєць Долгу
  icon: Dolg
  description: Захисник людства.
  playTimeTracker: JobDolg
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobDolg
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: DolgGear
  supervisors: Ви підкоряєтеся старшим за званням.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Dolg
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: Dolg
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerHeadDolg
  name: Лидер Обов'язку
  icon: Dolg
  description: Захисник людства.
  playTimeTracker: JobHeadDolg
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadDolg
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: DolgGear
  supervisors: Ви командуєте іншими бійцями Долга.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Dolg
            - DolgHead
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: Dolg
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: DolgGear
  equipment:
    id: DolgPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansDolgCamouflage
    shoes: ClothingShoesBootsWork
    torso: ClothingTorsoTurtlenecksDolgCamouflage
    cloak: ClothingNeckCloakDolg
