- type: job
  id: MilitaryStalker
  name: Military stalker
  icon: voen
  description: Soldiers who have undergone special training after their experience of service in the Zone, or stalkers who have signed a contract with the army.
  playTimeTracker: JobMilitaryStalker
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitaryStalker
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitarySpecGear
  supervisors: Ты будешь терпеть и страдать, Victoria cruenta
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - MilitaryStalker
      - type: Bands
        altBand: stalker
        canChange: true
        band: Stalker
        bandIcon: voen
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: Military
  name: Military
  icon: army
  description: Maintain the Zone to prevent the looting of hazardous radioactive materials and to prevent unauthorized entry by any persons.
  playTimeTracker: JobMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Вы подчиняетесь старшим по званию.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Military
      - type: Bands
        band: Stalker
        bandIcon: army
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: job
  id: MilitaryHead
  name: Head of the Military
  icon: army
  description: Maintain the Zone to prevent the looting of hazardous radioactive materials and to prevent unauthorized entry by any persons.
  playTimeTracker: JobHeadMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Вы подчиняетесь старшим по званию.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryHead
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: MilitaryOfficer
  name: Military Officer
  icon: army
  description: Maintain the Zone to prevent the looting of hazardous radioactive materials and to prevent unauthorized entry by any persons.
  playTimeTracker: JobOfficerMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobOfficerMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Вы подчиняетесь старшим по званию.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryOfficer
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems

- type: startingGear
  id: MilitaryGear
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesPortyanki
    head: STClothingHeadTinfoil

- type: startingGear
  id: MilitaryGearHead
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltAssault
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesPortyanki
    head: STClothingHeadTinfoil
    pocket1: STJobMilitaryIDCard

- type: startingGear
  id: MilitarySpecGear
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesBootsCombatFilled

- type: startingGear
  id: OksopSpecOps
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltMercWebbingStalker
    mask: ClothingMaskNeckBalaklava3
    back: ClothingBackpackDuffelCommonStalker
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesBootsCombat
    outerarmor: STClothingOuterArmorLightPlateVestBaseHeavyMilitary
    pocket1: 739Mag75
    pocket2: 739Mag75
    suitstorage: STWeaponRifleStalkerAK103
