- type: entity
  parent: ClothingOuterBaseLarge
  id: STFireProtectionSuit
  name: fireman costume
  suffix: ST, T2, Env
  description: Designed for high temperatures
  components:
  - type: Sprite
    sprite: _Stalker/Objects/Clothing/outerClothing/firesuit.rsi
  - type: Clothing
    sprite: _Stalker/Objects/Clothing/outerClothing/firesuit.rsi
  - type: PressureProtection
    highPressureMultiplier: 0.04
  - type: TemperatureProtection
    coefficient: 0.005
  - type: STWeight
    self: 7
  - type: Armor
    armorClass: 1
    modifiers:
      flatReductions:
        Heat: 2
      coefficients:
        Heat: 0.5
  - type: ClothingSpeedModifier
    walkModifier: 0.8
    sprintModifier: 0.7
  - type: ToggleableClothing
    clothingPrototype: STFireProtectionHelmet
    slot: head
  - type: HeldSpeedModifier
  - type: GroupExamine

- type: entity
  parent: ClothingHeadLightBase
  id: STFireProtectionHelmet
  name: firemans helmet
  suffix: ST
  description: Thermal insulating helmet
  noSpawn: true
  components:
  - type: Sprite
    sprite: _Stalker/Objects/Clothing/hats/fireprotecthelmet.rsi
  - type: Clothing
    sprite: _Stalker/Objects/Clothing/hats/fireprotecthelmet.rsi
  - type: TemperatureProtection
    coefficient: 0.005
  - type: Armor
    modifiers:
      flatReductions:
        Heat: 2
  - type: Tag
    tags:
    - HidesHair
